python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P01-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P01-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P02-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P02-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P03-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P03-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P04-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P04-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P05-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P05-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P06-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P06-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P07-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P07-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P08-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P08-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P09-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P09-pca_max.pkl

python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P10-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P10-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P11-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P11-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P12-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P12-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P13-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P13-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P14-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P14-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P15-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P15-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P16-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P16-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P17-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P17-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P18-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P18-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P19-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P19-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P20-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P20-pca_max.pkl
python3 -u ../bullets/pca_decompose.py -s data/skgest-smpl-center-folds-fill_0-raw-origin/fold-P21-origin.pkl -d data/skgest-smpl-center-folds-fill_0-raw-pca_max/fold-P21-pca_max.pkl
