python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P01.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P01-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P02.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P02-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P03.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P03-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P04.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P04-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P05.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P05-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P06.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P06-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P07.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P07-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P08.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P08-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P09.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P09-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P10.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P10-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P11.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P11-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P12.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P12-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P13.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P13-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P14.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P14-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P15.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P15-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P16.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P16-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P17.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P17-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P18.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P18-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P19.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P19-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P20.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P20-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-mpipe-center-folds/fold-P21.npz -d data/skgest-mpipe-center-folds-ffill-raw-origin/fold-P21-origin.pkl

python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P01.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P01-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P02.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P02-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P03.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P03-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P04.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P04-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P05.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P05-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P06.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P06-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P07.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P07-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P08.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P08-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P09.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P09-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P10.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P10-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P11.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P11-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P12.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P12-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P13.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P13-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P14.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P14-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P15.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P15-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P16.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P16-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P17.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P17-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P18.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P18-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P19.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P19-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P20.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P20-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-smpl-center-folds/fold-P21.npz -d data/skgest-smpl-center-folds-ffill-raw-origin/fold-P21-origin.pkl

python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P01.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P01-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P02.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P02-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P03.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P03-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P04.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P04-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P05.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P05-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P06.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P06-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P07.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P07-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P08.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P08-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P09.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P09-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P10.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P10-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P11.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P11-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P12.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P12-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P13.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P13-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P14.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P14-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P15.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P15-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P16.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P16-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P17.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P17-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P18.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P18-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P19.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P19-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P20.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P20-origin.pkl
python3 -u ../bullets/origin_decompose.py -s data/initial_and_old/skgest-ntu-center-folds/fold-P21.npz -d data/skgest-ntu-center-folds-ffill-raw-origin/fold-P21-origin.pkl
